export { RenderProps1 } from "./class-2-RenderProps1";
export { RenderProps2 } from "./class-2-RenderProps2";
export { ControlProps } from "./class-3-ControlProps";
export { CompoundComponents } from "./class-4-CompoundComponents";
export { HighOrderComponent } from "./class-5-HighOrderComponent";
export { CustomHooks } from "./class-6-CustomHooks";
export { ContainerPresenter } from "./class-7-ContainerPresenter";
export { ControlledComponent } from "./class-8-ControlledComponent";
export { UncontrolledComponent } from "./class-8-UncontrolledComponent";
